[package]
name = "ekman_core"
edition.workspace = true
version.workspace = true

[dependencies]
serde = { version = "1.0", features = ["derive"] }
chrono = { version = "0.4", features = ["serde"] }

[dev-dependencies]
serde_json = "1.0"
serde_urlencoded = "0.7"
