[package]
name = "core"
edition.workspace = true
version.workspace = true

[lib]
name = "ekman_core"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
chrono = { version = "0.4", features = ["serde"] }
thiserror = "1.0"
